version: '3'
services:
    ml_base:
        image: ml_base
        build: .
        volumes:
            - ./local:/app
        ports:
            - "8888:8888"
        command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root --notebook-dir=/app/notebook
